//! Ethereum Light Client verification program for SP1 zkVM.
//!
//! This program runs inside the zkVM and verifies a light client update:
//! 1. Validates sync committee participation (>= threshold)
//! 2. Verifies the finality Merkle proof (finalized header in attested state)
//! 3. Verifies sync committee rotation proof (if present)
//! 4. Computes domain & signing root for BLS context
//! 5. [Phase 3] Verifies L1 storage proofs (MPT) against finalized state root
//! 6. [Phase 3] Verifies L2 state via L2OutputOracle on L1
//! 7. Commits verified public values (finalized slot, roots, committee hashes,
//!    storage proof results)
//!
//! The proof generated by SP1 attests that these verification steps passed,
//! enabling trustless on-chain verification of Ethereum consensus AND execution state.

#![no_main]
sp1_zkvm::entrypoint!(main);

use alloy_sol_types::SolType;
use eth_lc_lib::{
    consensus::verify_light_client_update,
    types::{Address, Bytes32, ProofInputs},
    LightClientPublicValues,
};

pub fn main() {
    // Read the proof inputs from the prover (host/script).
    let inputs = sp1_zkvm::io::read::<ProofInputs>();

    // =========================================================================
    // Step 1: Verify consensus (participation, Merkle proofs, signing root)
    // =========================================================================
    let result = verify_light_client_update(&inputs)
        .expect("Light client update verification failed");

    // =========================================================================
    // Step 2: Verify L1 storage proofs (if present)
    // =========================================================================
    let (num_storage_slots, storage_proof_address, storage_proof_storage_root) =
        if let Some(ref sp) = inputs.storage_proof {
            // Verify account proof against the finalized execution state root.
            let account = eth_lc_lib::mpt::verify_account_proof(
                &sp.address,
                &sp.account_proof,
                &result.finalized_state_root,
            )
            .expect("L1 account proof verification failed");

            // Verify each storage slot proof against the account's storage root.
            for (i, slot_proof) in sp.storage_proofs.iter().enumerate() {
                eth_lc_lib::mpt::verify_storage_proof(
                    &slot_proof.key,
                    &slot_proof.proof,
                    &account.storage_root,
                )
                .unwrap_or_else(|e| panic!("L1 storage proof #{i} failed: {e:?}"));
            }

            let mut addr = Address::default();
            addr.copy_from_slice(&sp.address);

            (
                sp.storage_proofs.len() as u32,
                addr,
                account.storage_root,
            )
        } else {
            (0u32, Address::default(), Bytes32::default())
        };

    // =========================================================================
    // Step 3: Verify L2 state via L2OutputOracle (if present)
    // =========================================================================
    let (num_l2_slots, l2_state_root) = if let Some(ref l2) = inputs.l2_storage_proof {
        // Full L2 verification pipeline:
        // 1. Verify oracle account on L1
        // 2. Read output root from oracle storage
        // 3. Verify L2OutputRoot components match proven output root
        // 4. Verify L2 account against L2 state root
        let l2_account = eth_lc_lib::l2::verify_l2_account(
            &l2.oracle_address,
            &l2.oracle_account_proof,
            &result.finalized_state_root,
            l2.output_index,
            &l2.output_root_storage_proof,
            &l2.l2_output,
            &l2.l2_address,
            &l2.l2_account_proof,
        )
        .expect("L2 account verification failed");

        // 5. Verify L2 storage proofs
        for (i, slot_proof) in l2.l2_storage_proofs.iter().enumerate() {
            eth_lc_lib::l2::verify_l2_storage(
                &slot_proof.key,
                &slot_proof.proof,
                &l2_account.storage_root,
            )
            .unwrap_or_else(|e| panic!("L2 storage proof #{i} failed: {e}"));
        }

        (
            l2.l2_storage_proofs.len() as u32,
            l2.l2_output.state_root,
        )
    } else {
        (0u32, Bytes32::default())
    };

    // =========================================================================
    // Step 4: Encode and commit public values
    // =========================================================================
    let bytes = LightClientPublicValues::abi_encode(&LightClientPublicValues {
        finalizedSlot: result.finalized_slot,
        finalizedHeaderRoot: result.finalized_header_root.into(),
        finalizedStateRoot: result.finalized_state_root.into(),
        currentSyncCommitteeHash: result.current_sync_committee_hash.into(),
        nextSyncCommitteeHash: result.next_sync_committee_hash.into(),
        participation: result.participation,
        numStorageSlots: num_storage_slots,
        storageProofAddress: alloy_sol_types::private::Address::from(storage_proof_address),
        storageProofStorageRoot: storage_proof_storage_root.into(),
        numL2StorageSlots: num_l2_slots,
        l2StateRoot: l2_state_root.into(),
    });

    // Commit the public values to the proof.
    sp1_zkvm::io::commit_slice(&bytes);
}
